### ISSUE TITLE
Audit Plugin: ERROR: unable to connect to socket: /var/run/db-audit/postgresql.audit__u02_pgdata01_data_5432. err: No such file or directory."

### ISSUE THREAD

**Issue by dkumarr2** [mcafee/postgresql-audit#1]
Hi Team,

when we completed the postgres audit plugin installation in our servers, we are getting an error message in log file as "Audit Plugin: ERROR: unable to connect to socket: /var/run/db-audit/postgresql.audit__u02_pgdata01_data_5432. err: No such file or directory.". Can you guide us on how to resolve this error.

Thanks

**Comment by ghost** [comment]
Hi.

Please make sure that the configuration setting **audit.json_unix_socket** is set to OFF.

**Comment by ghost** [comment]
Hi. Did this work for you?  Thanks.

**Comment by dkumarr2** [comment]
Thanks for the suggestion. It was worked for creating the audit.json file. But still this file /var/run/db-audit/postgresql.audit__u02_pgdata01_data_5432. err not created.

**Comment by ghost** [comment]
Setting **audit.json_unix_socket** to OFF should have done the trick.  Do you want to upload your PostgreSQL configuration file for me to review?

**Comment by dkumarr2** [comment]
audit.json_file=1
audit.json_unix_socket=1
audit.json_file_name='/u02/pgdata01/data/audit.json'
audit.json_unix_socket_name='/var/run/db-audit/postgresql.audit__u02_pgdata01_data_5432'
audit.header_msg=on
audit.debug_logs=on
isecgaudit.debug_logs=1

This will be configuration parameters added for audit plugin in Postgres. Can you please check and let me know why  this file /var/run/db-audit/postgresql.audit__u02_pgdata01_data_5432. err not created.

**Comment by ghost** [comment]
Thanks for the info.

You do not need the file /var/run/db-audit/postgresql.audit__u02_pgdata01_data_5432..  It is for use by our proprietary Database Monitoring product, and that product creates the socket file.  You should remove the two lines

audit.json_unix_socket=1
audit.json_unix_socket_name='/var/run/db-audit/postgresql.audit__u02_pgdata01_data_5432'

from your configuration file and restart PostgreSQL.

(As a side note, you also should not need the line

isecgaudit.debug_logs=1

in your config.)

I hope this helps.

**Comment by dkumarr2** [comment]
thanks, I will do it

**Comment by dkumarr2** [comment]
Also one question,  is this possible to add multiple cluster information (different host and different port) in pgbouncer.ini file. As both the cluster will access the same port in pgbouncer, I'm getting confuse. Can you please let me know about it

**Comment by ghost** [comment]
I don't know anything about pgbouncer ... Sorry.

**Comment by dkumarr2** [comment]
oh k. no problem

**Comment by dkumarr2** [comment]
"Audit Plugin: WARNING: audit stack is not empty",,,,,,"create table test2(id numeric);",,,"psql.bin"

This is the warning I got while running DDL queries.

**Comment by ghost** [comment]
I had a brief discussion with a team member.  Basically, you can ignore this error. If it's really bothering you, you can remove the message (or change the severity) and recompile the plugin.  We hope to address this in a future release.

**Comment by dkumarr2** [comment]
audit.json_file=1 this parameter is required?

**Comment by ghost** [comment]
It is needed in order to have the plugin log events in JSON format to a file.  Without it, the plugin is transparent and does nothing.

**Comment by dkumarr2** [comment]
many thanks
