### ISSUE TITLE
FATAL: incompatible library "/opt/edb/as9.6/lib/audit.so": magic block mismatch ; DETAIL:  Server has FUNC_MAX_ARGS = 256, library has 100

### ISSUE THREAD

**Issue by mohdshamsalam** [mcafee/postgresql-audit#2]
Hi Team,

We are trying to configure audit plugin for EDB Postgres - 9.6. We are getting the below error while starting the EDB service.

FATAL: incompatible library "/opt/edb/as9.6/lib/audit.so": magic block mismatch
DETAIL:  Server has FUNC_MAX_ARGS = 256, library has 100

Please guide us to resolve this error.

Thanks.

**Comment by ghost** [comment]
Hi. This is a new one on us.

The pre-compiled plugins are compiled against the source for the regular PostgreSQL distributions, not for EDB PostgreSQL.  Your best bet would be to compile the plugin from source against the EDB PostgreSQL sources.

We will also try to investigate this.

Thanks.

**Comment by ghost** [comment]
Hi.  We have started investigating this.

We cannot support the "Enterprise" version of EDB PostgreSQL at this time, but have started looking into what it would take to be able to do so.

In preliminary testing with the "Standard" version of EDB PostgreSQL, our plugin works. We will be doing more thorough internal validation on this version.  If you can move to this version, you should be able to use the plugin.

Hope this helps,

Aharon

**Comment by ghost** [comment]
Hi. We have just added support for EDB Postgres Enterprise 9.6.2.7.  It should work on any EDB Postgres Enterprise 9.6.x release.  Please download the latest dev-snapshot version from https://bintray.com/mcafee/postgresql-audit-plugin/dev-snapshot.

**Comment by TomerHadri** [comment]
Hi. We have made a formal release that includes support for EDB Postgres Enterprise 9.4 through 9.6. Please download the latest release version from https://bintray.com/mcafee/postgresql-audit-plugin/release. Closing this issue.
